# Generated by Django 2.2.5 on 2019-09-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redditOptimizer', '0002_outputbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutputBox',
        ),
    ]
