# Generated by Django 2.2.5 on 2019-09-14 07:17

import RedditOptApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditOptApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddits', RedditOptApi.models.ListField(token=',')),
            ],
        ),
    ]
