# Generated by Django 2.2.5 on 2019-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedditOptApi', '0002_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputbox',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inputbox',
            name='return_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
